### ISSUE TITLE
Add installer to ./pro script that handles npm installs in tools/

### ISSUE THREAD

**Issue by tkali** [madmaniak/pro#2]
Each `nodejs`-based tool in `tools/` has separate `package.json` that requires `npm install` action in respective directories. 

**Proposal**: Define installers like `./pro --install web` or `./pro --install desktop` that will walk through these directories and install dependencies.

**Comment by madmaniak** [comment]
I think this will be solved by the deployment tool which will create services - probably on docker - you can run everywhere production or locally.

**Comment by madmaniak** [comment]
Done https://github.com/madmaniak/pro/commit/aa00cce5f90a04094f1620fecfad786edf3f3c1b
